### ISSUE TITLE
mseed exec names

### ISSUE THREAD

**Issue by crotwell** [iris-edu/mseed3-utils#23]
Just a thought, but since this is dealing with mseed3, it is a little confusing to have some commands named like mseed2json and some like mseed3-validator. Perhaps mseed3-json and mseed3-text. Otherwise they look like they might deal with miniseed version 2.

**Comment by chad-iris** [comment]
Yep, thought the same and I like that suggestion, thanks.

**Comment by chad-iris** [comment]
Names changed.
